[legends]
U_EXLM = !
KC_EXLM = !
U_QUES = ? !
KC_QUES = ? !
KC_GT = >
KC_LT = <
KC_HASH = #
KC_PERC = %
KC_AT = @
KC_DLR = $
KC_CIRC = ^
KC_LCBR = {
KC_LPRN = (
KC_LBRC = [
KC_RCBR = }
KC_RPRN = )
KC_RBRC = ]
KC_PIPE = |
KC_GRV = `
KC_TILD = ~
KC_PLUS = +
KC_AMPR = &
KC_UNDS = _
KC_MINS = - _
KC_EQL = =
U_SL = / \
KC_SLSH = / ?
U_COMM = , <
KC_COMM = , <
KC_DOT = . >
KC_ASTR = *
KC_BSLS = \ |
KC_BSLASH = \ |
U_QUOT = ' "
KC_QUOT = ' "
KC_SCLN = : ;
KC_PSCR = PrintSc
KC_NLCK = NumLock
KC_SLCK = ScrLock
KC_INS = Ins
_ =
__ =

KC_MS_U = MSE ↑
KC_MS_D = MSE ↓
KC_MS_L = MSE ←
KC_MS_R = MSE →
KC_WH_U = WHEEL ↑
KC_WH_D = WHEEL ↓
KC_WBAK = ⯬
KC_WFWD = ⯮

KC_LGUI = L⌘
KC_RGUI = R⌘
KC_LALT = L⎇
KC_RALT = R⎇
KC_LSFT = L⇧
KC_RSFT = R⇧
KC_LCTL = L^
KC_RCTL = R^

HM_A = A/^
HM_D = D/⌘
HM_F = F/⇧
HM_J = J/⇧
HM_K = K/⌘
HM_L = L/⎇
HM_S = S/⎇
HM_SCLN = ;/^

SPOT = SPTLGHT

KC_LEFT = ◁
KC_DOWN = ▽
KC_UP = △
KC_RIGHT = ▷

NAV_SPC = SPC/NAV
SYM_BSP = BSP/SYM
SYM_SPOT = SPOT/SYM

G(KC_X) = CUT
G(KC_C) = COPY
G(KC_V) = PASTE
G(KC_Z) = UNDO

MS_CAPS = CAPS/MS
NAV_UND = _/NAV

OS_LSFT = 1-SHOT⇧
OS_RSFT = 1-SHOT⇧

ARROW_R = -> =>

# macros
UPDIR = ../
O_BRACE = {⏎
C_BRACE = }⏎

TD_DOT = . >
OSM_LSFT = LSFT
OSM_LCTL = LCTL