#include "action.h"
#include QMK_KEYBOARD_H
#include <stdio.h>
#include "keymap.h"
#include "features/achordion.h"

#define OSM_LCTL OSM(MOD_LCTL)
#define OSM_LSFT OSM(MOD_LSFT)

// clang-format off
const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
/* ┌──────┬──────┬──────┬──────┬──────┬──────┐                    ┌──────┬──────┬──────┬──────┬──────┬──────┐
 * │ ESC  │  1   │  2   │  3   │  4   │  5   │                    │  6   │  7   │  8   │  9   │  0   │ DEL  │
 * ├──────┼──────┼──────┼──────┼──────┼──────┤                    ├──────┼──────┼──────┼──────┼──────┼──────┤
 * │  `   │  Q   │  W   │  E   │  R   │  T   │                    │  Y   │  U   │  I   │  O   │  P   │MINUS │
 * ├──────┼──────┼──────┼──────┼──────┼──────┤                    ├──────┼──────┼──────┼──────┼──────┼──────┤
 * │ TAB  │ A/^  │ S/⎇  │ D/⌘  │ F/⇧  │  G   │┌──────┐    ┌──────┐│  H   │ J/⇧  │ K/⌘  │ L/⎇  │ ;/^  │ ' "  │
 * ├──────┼──────┼──────┼──────┼──────┼──────┤│ MUTE │    │      │├──────┼──────┼──────┼──────┼──────┼──────┤
 * │ LCTL │  Z   │  X   │  C   │  V   │  B   │└──────┘    └──────┘│  N   │  M   │ , <  │ . >  │ / ?  │  R⇧  │
 * └──────┴──────┼──────┼──────┼──────┼──────┼───────┐    ┌───────┼──────┼──────┼──────┼──────┼──────┴──────┘
 *               │ HYPR │      │ ESC  │SPC/NA│SPOT/SY│    │  ENT  │BSP/SY│ LSFT │  R⎇  │      │
 *               │      │      │      │      │       │    │       │      │      │      │      │
 *               └──────┴──────┴──────┴──────┴───────┘    └───────┴──────┴──────┴──────┴──────┘
 *                                                                                   generated by [keymapviz] */
[_QWERTY] = LAYOUT(
  KC_ESC,   KC_1,   KC_2,    KC_3,    KC_4,    KC_5,                      KC_6,    KC_7,    KC_8,    KC_9,   KC_0,    KC_DEL,
  KC_GRV,   KC_Q,   KC_W,    KC_E,    KC_R,    KC_T,                      KC_Y,    KC_U,    KC_I,    KC_O,   KC_P,    KC_MINUS,
  KC_TAB,   HM_A,   HM_S,    HM_D,    HM_F,    KC_G,                      KC_H,    HM_J,    HM_K,    HM_L,   HM_SCLN, KC_QUOT,
  OSM_LCTL, KC_Z,   KC_X,    KC_C,    KC_V,    KC_B, KC_MUTE,    XXXXXXX, KC_N,    KC_M,    KC_COMM, KC_DOT, KC_SLSH, KC_RSFT,
                 KC_HYPR, XXXXXXX, KC_ESC, NAV_SPC, SYM_SPOT,    KC_ENT,  SYM_BSP, OSM_LSFT,KC_RALT, XXXXXXX
),
/* ┌──────┬──────┬──────┬──────┬──────┬──────┐                    ┌──────┬──────┬──────┬──────┬──────┬──────┐
 * │      │  F1  │  F2  │  F3  │  F4  │  F5  │                    │  F6  │  F7  │  F8  │  F9  │ F10  │ F11  │
 * ├──────┼──────┼──────┼──────┼──────┼──────┤                    ├──────┼──────┼──────┼──────┼──────┼──────┤
 * │  `   │  !   │  @   │  #   │  {   │  }   │                    │      │ ../  │  {⏎  │  }⏎  │      │  |   │
 * ├──────┼──────┼──────┼──────┼──────┼──────┤                    ├──────┼──────┼──────┼──────┼──────┼──────┤
 * │CAPSWR│  $   │  %   │  ^   │  (   │  )   │┌──────┐    ┌──────┐│      │  +   │  =   │FARROW│      │      │
 * ├──────┼──────┼──────┼──────┼──────┼──────┤│ MPLY │    │      │├──────┼──────┼──────┼──────┼──────┼──────┤
 * │      │  &   │  *   │  `   │  [   │  ]   │└──────┘    └──────┘│      │  _   │ - _  │ARROW │      │      │
 * └──────┴──────┼──────┼──────┼──────┼──────┼───────┐    ┌───────┼──────┼──────┼──────┼──────┼──────┴──────┘
 *               │      │      │ NAV  │      │       │    │       │      │      │      │      │
 *               │      │      │      │      │       │    │       │      │      │      │      │
 *               └──────┴──────┴──────┴──────┴───────┘    └───────┴──────┴──────┴──────┴──────┘
 *                                                                                   generated by [keymapviz] */
[_SYM] = LAYOUT(
  _______,  KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,                           KC_F6,   KC_F7,    KC_F8,   KC_F9,   KC_F10,   KC_F11,
  KC_GRV,   KC_EXLM, KC_AT,   KC_HASH, KC_LCBR, KC_RCBR,                         _______, UPDIR,    O_BRACE, C_BRACE, _______, KC_PIPE,
  CAPSWRD,  KC_DLR,  KC_PERC, KC_CIRC, KC_LPRN, KC_RPRN,                         _______, KC_PLUS,  KC_EQL,  FARROW,  _______, _______,
  _______,  KC_AMPR, KC_ASTR, KC_GRV,  KC_LBRC, KC_RBRC, KC_MPLY,       _______, _______, KC_UNDS,  KC_MINS, ARROW,   _______, _______,
                     _______, _______,     NAV, _______, _______,       _______, _______, _______, _______, _______
),
/* ┌──────┬──────┬──────┬──────┬──────┬──────┐                    ┌──────┬──────┬──────┬──────┬──────┬──────┐
 * │      │  F1  │  F2  │  F3  │  F4  │  F5  │                    │  F6  │  F7  │  F8  │  F9  │ F10  │ F11  │
 * ├──────┼──────┼──────┼──────┼──────┼──────┤                    ├──────┼──────┼──────┼──────┼──────┼──────┤
 * │      │  1   │  2   │  3   │  4   │  5   │                    │  6   │  7   │  8   │  9   │  0   │ DEL  │
 * ├──────┼──────┼──────┼──────┼──────┼──────┤                    ├──────┼──────┼──────┼──────┼──────┼──────┤
 * │      │  L^  │  L⎇  │  L⌘  │  L⇧  │      │┌──────┐    ┌──────┐│  ◁   │  ▽   │  △   │  ▷   │      │      │
 * ├──────┼──────┼──────┼──────┼──────┼──────┤│      │    │      │├──────┼──────┼──────┼──────┼──────┼──────┤
 * │      │ UNDO │ CUT  │ COPY │PASTE │      │└──────┘    └──────┘│      │      │      │ . >  │ \ |  │      │
 * └──────┴──────┼──────┼──────┼──────┼──────┼───────┐    ┌───────┼──────┼──────┼──────┼──────┼──────┴──────┘
 *               │      │      │      │      │       │    │       │      │      │      │      │
 *               │      │      │      │      │       │    │       │      │      │      │      │
 *               └──────┴──────┴──────┴──────┴───────┘    └───────┴──────┴──────┴──────┴──────┘
 *                                                                                   generated by [keymapviz] */
[_NAV] = LAYOUT(
  _______,  KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,                           KC_F6,   KC_F7,    KC_F8,   KC_F9,    KC_F10,   KC_F11,
  _______,  KC_1,    KC_2,    KC_3,    KC_4,    KC_5,                            KC_6,    KC_7,     KC_8,    KC_9,     KC_0,     KC_DEL,
  _______,  KC_LCTL, KC_LALT, KC_LGUI, KC_LSFT, _______,                         KC_LEFT, KC_DOWN,  KC_UP,   KC_RIGHT, _______, _______,
  _______,  G(KC_Z), G(KC_X), G(KC_C), G(KC_V), _______, _______,       _______, _______, _______,  _______, KC_DOT,   KC_BSLS, _______,
                     _______, _______, _______, _______, _______,       _______, _______, _______, _______, _______
),
/* ┌──────┬──────┬──────┬──────┬──────┬──────┐                    ┌──────┬──────┬──────┬──────┬──────┬──────┐
 * │      │      │      │      │      │      │                    │      │      │      │      │      │      │
 * ├──────┼──────┼──────┼──────┼──────┼──────┤                    ├──────┼──────┼──────┼──────┼──────┼──────┤
 * │RESET │      │      │      │CG_TOG│      │                    │      │      │      │      │      │      │
 * ├──────┼──────┼──────┼──────┼──────┼──────┤                    ├──────┼──────┼──────┼──────┼──────┼──────┤
 * │      │      │CG_TOG│      │      │      │┌──────┐    ┌──────┐│      │ VOLD │ MUTE │ VOLU │      │      │
 * ├──────┼──────┼──────┼──────┼──────┼──────┤│      │    │      │├──────┼──────┼──────┼──────┼──────┼──────┤
 * │      │      │      │      │      │      │└──────┘    └──────┘│      │ MPRV │ MPLY │ MNXT │      │      │
 * └──────┴──────┼──────┼──────┼──────┼──────┼───────┐    ┌───────┼──────┼──────┼──────┼──────┼──────┴──────┘
 *               │      │      │      │      │       │    │       │      │      │      │      │
 *               │      │      │      │      │       │    │       │      │      │      │      │
 *               └──────┴──────┴──────┴──────┴───────┘    └───────┴──────┴──────┴──────┴──────┘
 *                                                                                   generated by [keymapviz] */
  [_ADJUST] = LAYOUT(
  XXXXXXX , XXXXXXX,  XXXXXXX,  XXXXXXX , XXXXXXX, XXXXXXX,                     XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
  RESET  , XXXXXXX,   XXXXXXX, XXXXXXX,CG_TOGG,XXXXXXX,                     XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
  XXXXXXX , XXXXXXX,CG_TOGG, XXXXXXX,    XXXXXXX,  XXXXXXX,                     XXXXXXX, KC_VOLD, KC_MUTE, KC_VOLU, XXXXXXX, XXXXXXX,
  XXXXXXX , XXXXXXX, XXXXXXX, XXXXXXX,    XXXXXXX,  XXXXXXX, XXXXXXX,     XXXXXXX, XXXXXXX, KC_MPRV, KC_MPLY, KC_MNXT, XXXXXXX, XXXXXXX,
                   _______, _______, _______, _______, _______,     _______, _______, _______, _______, _______
  )
};

void matrix_scan_user(void) {
  achordion_task();
}

bool process_record_user(uint16_t keycode, keyrecord_t *record) {
  if (!process_achordion(keycode, record)) { return false; }
  
  switch (keycode) {
    case SYM_SPOT:
      if (record->tap.count && record->event.pressed) {
        tap_code16(A(KC_SPC));
        return false;
      }
      break;
  case UPDIR:
    if (record->event.pressed) {
      tap_code(KC_DOT);
      tap_code(KC_DOT);
      tap_code(KC_SLASH);
    }
    return false;
  case O_BRACE:
    if (record->event.pressed) {
      tap_code16(KC_LEFT_CURLY_BRACE);
      tap_code(KC_ENTER);
    }
    return false;
  case C_BRACE:
    if (record->event.pressed) {
      tap_code16(KC_RIGHT_CURLY_BRACE);
      tap_code(KC_ENTER);
    }
    return false;
  case FARROW:
    if (record->event.pressed) {
      SEND_STRING("=>");
    }
    return false;
  case ARROW:
    if (record->event.pressed) {
      SEND_STRING("->");
    }
    return false;
  }
  return true;
}

bool achordion_chord(uint16_t tap_hold_keycode,
                     keyrecord_t* tap_hold_record,
                     uint16_t other_keycode,
                     keyrecord_t* other_record) {
  // do not affect behaviour if the other key is not on the home row
  if (other_record->event.key.row != tap_hold_record->event.key.row) { return true; }
  // do not affect outer rows (for one-handed alt-tab)
  if (other_record->event.key.col == 0 || other_record->event.key.col == (MATRIX_COLS - 1)) { return true; }

  return achordion_opposite_hands(tap_hold_record, other_record);
}

uint16_t achordion_timeout(uint16_t tap_hold_keycode) {
  return 800;
}

#ifdef TAPPING_FORCE_HOLD_PER_KEY
bool get_tapping_force_hold(uint16_t keycode, keyrecord_t *record) {
  // only allow certain keys to repeat after being tapped. this is mainly for vim navigation
  switch (keycode) {
  case HM_J:
  case HM_K:
  case HM_L:
  case HM_SCLN:
  case SYM_BSP:
    // false means do not force hold - treat as tap
    return false;
  default:
    return true;
  }
}
#endif

#ifdef TAPPING_TERM_PER_KEY
uint16_t get_tapping_term(uint16_t keycode, keyrecord_t *record) {
    switch (keycode) {
        case HM_F:
        case HM_J:
          // lower tapping term of shifts
            return TAPPING_TERM - 30;
        default:
            return TAPPING_TERM;
    }
};
#endif

#ifdef OLED_ENABLE

char wpm_text[9];
static void print_wpm(void) {
    int currwpm = get_current_wpm();
    sprintf(wpm_text, "WPM: %i", currwpm);
    oled_write_P(PSTR("\n\n\n"), false);
    oled_write_ln(wpm_text, false);
}

static void print_status_narrow(void) {
    // Print current mode
    oled_write_P(PSTR("\n\n"), false);
    oled_write_P(PSTR("JAKE"), false);
    oled_write_P(PSTR("\n\n"), false);
    // Print current layer
    oled_write_ln_P(PSTR("LAYER"), false);
    switch (get_highest_layer(layer_state)) {
        case _QWERTY:
            oled_write_P(PSTR("BASE\n"), false);
            break;
        case _NAV:
            oled_write_P(PSTR("NAV\n"), false);
            break;
        case _SYM:
            oled_write_P(PSTR("SYM\n"), false);
            break;
        case _ADJUST:
            oled_write_P(PSTR("ADJ\n"), false);
            break;
        default:
            oled_write_ln_P(PSTR("???"), false);
    }
    oled_write_P(PSTR("\n\n"), false);
    oled_write_ln_P(PSTR("WCAPS"), is_caps_word_on());
}

oled_rotation_t oled_init_user(oled_rotation_t rotation) {
    if (is_keyboard_master()) {
        return OLED_ROTATION_270;
    }
    /* return rotation; */
    return OLED_ROTATION_270;
}

bool oled_task_user(void) {
    if (is_keyboard_master()) {
        print_status_narrow();
    } else {
        print_wpm();
    }
    return false;
}

#endif

// activate adjust layer
layer_state_t layer_state_set_user(layer_state_t state) {
  return update_tri_layer_state(state, _NAV, _SYM, _ADJUST);
}

#ifdef ENCODER_ENABLE

bool encoder_update_user(uint8_t index, bool clockwise) {
    if (index == 0) {
      if (layer_state_is(_SYM)) {
          if (clockwise) {
            tap_code(KC_MNXT);
        } else {
            tap_code(KC_MPRV);
        }
      } else {
          if (clockwise) {
            tap_code(KC_VOLU);
        } else {
            tap_code(KC_VOLD);
        }
      }
    } else if (index == 1) {
        if (clockwise) {
            tap_code(KC_PGDOWN);
        } else {
            tap_code(KC_PGUP);
        }
    }
    return true;
}

#endif
